<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domainmodel" nsURI="domainmodel" nsPrefix="domainmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Customer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cashier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ready"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CardReader"/>
  <eClassifiers xsi:type="ecore:EClass" name="CashBox"/>
  <eClassifiers xsi:type="ecore:EClass" name="BarCodeScanner"/>
  <eClassifiers xsi:type="ecore:EClass" name="LightDisplay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CashDesk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lightDisplay" lowerBound="1"
        eType="#//LightDisplay" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentCashier" eType="#//Cashier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardReader" lowerBound="1"
        eType="#//CardReader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="barCodeScanner" lowerBound="1"
        eType="#//BarCodeScanner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cashBox" lowerBound="1"
        eType="#//CashBox"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="printer" lowerBound="1"
        eType="#//Printer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoreManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="StoreClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportingGui" lowerBound="1"
        eType="#//ReportingGUI" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inventory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="registeredSales" upperBound="-1"
        eType="#//Sale" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreditCard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1"
        eType="#//Customer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cash"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sale">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cashDesk" lowerBound="1"
        eType="#//CashDesk"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" lowerBound="1"
        eType="#//Payment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sellingFrequency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TradingSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="store" lowerBound="1" eType="#//Store"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bill">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sale" lowerBound="1" eType="#//Sale"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CashPayment" eSuperTypes="#//Payment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cash" lowerBound="1" eType="#//Cash"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CardPayment" eSuperTypes="#//Payment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="creditCard" lowerBound="1"
        eType="#//CreditCard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="black"/>
    <eLiterals name="green" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cashDesks" upperBound="-1"
        eType="#//CashDesk" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stocks" upperBound="-1"
        eType="#//Stock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventory" lowerBound="1"
        eType="#//Inventory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" upperBound="-1"
        eType="#//Supplier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderItems" upperBound="-1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stockItems" upperBound="-1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportingGUI"/>
  <eClassifiers xsi:type="ecore:EClass" name="Report"/>
  <eClassifiers xsi:type="ecore:EClass" name="Printer"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnterpriseManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enterprise">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stores" upperBound="-1"
        eType="#//Store" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//EnterpriseServer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnterpriseServer"/>
  <eClassifiers xsi:type="ecore:EClass" name="StoreServer"/>
</ecore:EPackage>
