<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="admission" nsURI="http://admission/1.0" nsPrefix="admission">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userAccount" lowerBound="1"
        eType="#//UserAccount"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserAccount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personalInfo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formerEducation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Admin">
    <eOperations name="addUser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegistrationForm">
    <eOperations name="submitForm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EducationForm"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserForm"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoginForm">
    <eOperations name="verifyData"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authData"/>
  </eClassifiers>
</ecore:EPackage>
